create table if not exists public.event_admin_options (
  id bigint generated by default as identity primary key,
  option_type text not null,
  option_value text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_admin_options_type_value_key unique (option_type, option_value)
);

create or replace function public.set_updated_at_event_admin_options()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_event_admin_options_updated_at on public.event_admin_options;
create trigger trg_event_admin_options_updated_at
before update on public.event_admin_options
for each row execute function public.set_updated_at_event_admin_options();

alter table public.event_admin_options enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'event_admin_options' and policyname = 'event_admin_options_read_authenticated'
  ) then
    create policy event_admin_options_read_authenticated
      on public.event_admin_options
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'event_admin_options' and policyname = 'event_admin_options_write_admin'
  ) then
    create policy event_admin_options_write_admin
      on public.event_admin_options
      for all
      to authenticated
      using (
        exists (
          select 1
          from public.profiles p
          where p.id = auth.uid()
            and coalesce(p.is_admin, false) = true
        )
      )
      with check (
        exists (
          select 1
          from public.profiles p
          where p.id = auth.uid()
            and coalesce(p.is_admin, false) = true
        )
      );
  end if;
end $$;

insert into public.event_admin_options (option_type, option_value, sort_order)
values
  ('event_type', 'Community Event', 1),
  ('event_type', 'School Event', 2),
  ('event_type', 'Town Service', 3),
  ('event_type', 'Festival', 4),
  ('event_type', 'Holiday Event', 5),
  ('event_type', 'Monthly Series', 6),
  ('category', 'General', 1),
  ('category', 'Family', 2),
  ('category', 'Food', 3),
  ('category', 'Music', 4),
  ('category', 'Vendor', 5),
  ('category', 'Parade', 6),
  ('category', 'Fundraiser', 7),
  ('category', 'Civic', 8),
  ('category', 'School', 9),
  ('category', 'Holiday', 10),
  ('area_label', 'Downtown', 1),
  ('area_label', 'Town Square', 2),
  ('area_label', 'Campus', 3),
  ('area_label', 'Community Wide', 4),
  ('area_label', 'Washington Street', 5),
  ('area_label', 'Courthouse Square', 6),
  ('vendor_category', 'Vendor', 1),
  ('vendor_category', 'Food', 2),
  ('vendor_category', 'Drink', 3),
  ('vendor_category', 'Craft', 4),
  ('vendor_category', 'Sponsor', 5),
  ('vendor_category', 'Info', 6),
  ('vendor_category', 'Multi Vendor', 7),
  ('page_tab', 'schedule', 1),
  ('page_tab', 'map', 2),
  ('page_tab', 'vendors', 3),
  ('page_tab', 'locations', 4),
  ('page_tab', 'flyer', 5),
  ('page_tab', 'resources', 6)
on conflict (option_type, option_value) do update
set sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();
